name: Request

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.event.number}}
      - run: echo ${{github.event.repository.name}}
        