name: Request

on:
  pull_request:
    branches:
    - master
    types: [closed]

jobs:
  job: 
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: curl "${{secrets.WEB_HOOK_URL}}?repository_name=${{github.event.repository.name}}&pull_request_number=${{github.event.number}}"
        